# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1f9e75164376ae4e6846f7f0872719d2b00fd33e9571e519d6542e65872d7b59ae7f77e08792e6481ee38c88591ee984215e1924e0438241390921d04cda7fb

test:
  secret_key_base: d286357ffd2665eacb4f45165b0e3c26173bd982a10ba315e088a97f0da93f148b714baeea1be7816c182eccbcf02cffcd439533e4a408ff0d0fd67f6d2e76f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
